### ISSUE TITLE
Repo settings (specifically .editorconfig end_of_line) cause CRLF/LF fights on Windows

### ISSUE THREAD

**Issue by RoystonS** [carbon-design-system/carbon-tutorial#235]
## carbon-tutorial settings cause clashes between tools which want to use CRLF and LF line-endings on Windows

- When I clone the repo with Windows, by default I get CRLF line endings.
- When I run `yarn ci-check`, I get warnings/errors because prettier uses the explicit `end_of_line = LF` setting from `.editorconfig` to assert that all the files should have LF line endings.
- When I run `yarn format`, _all_ of the source files - including ones I haven't touched, such as `.github/**` all get edited by prettier, forcing the line endings to LF.  (And just to clarify, it's not just listing all the filenames; it really is changing _all_ the files created during `git clone`, which all then appear as changed files and candidates for adding to a commit.)

The problem here is that we have one tool (git) that's wanting to use CRLF, and another explicit configuration (prettier, via `.editorconfig`) that wants to use LF.

I suspect this hasn't been spotted previously because most people are probably using Macs, where the default line-ending from a `git clone` is LF.

The result is that there's a battle between git and prettier.

The good news is that there are a few trivially-simple ways to resolve it:

1. remove the explicit LF setting from .editorconfig; prettier will then check that each file is self-consistent, and git will do whatever it needs (typically involving converting CRLF files to LF files at commit time).  The explicit entry doesn't need to be there: on a Mac, files will be created as LF and checked-in by git as LF by default; on Windows files will be created as CRLF and checked in by git as LF.
1. add explicit `.gitattributes` entries to make the git behaviour match that of the `.editorconfig` settings; this is a bit fiddly, and a bit surprising for Windows users as some editors don't like pure-LF files.
1. tell every Windows user that they need to mess about with git's core.autocrlf to force the git clone to create LF-based files; this is the least friendly option.
1. do nothing, and tell every Windows user that they'll get weird behaviour, and that git will try to make them check in a bunch of files that haven't really changed;  actually, this is probably the least friendly option.

**Comment by mattrosno** [comment]
@RoystonS by default, `core.autocrlf` is false, meaning Windows does not convert LF to CRLF on checkout and does not convert back to LF on commit.

With option (1), we could then get CRLF committed and pushed upstream if a Windows user has not modified their `core.autocrlf` setting to `true` or `input`? That's a scenario that we want to avoid (mixed line endings upstream).

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace

I'm guessing this hasn't been an issue with Windows developers because they (a) haven't set `core.autocrlf` to a non-default value, and (b) they use a text editor that respects `.editorconfig` so files are saved with LF?

If my understanding of the default `core.autocrlf` is correct, I don't see a better option then (4) do nothing? Or am I missing something?

**Comment by RoystonS** [comment]
The official git docs actually recommend setting `core.autocrlf` to `true` on Windows, using `false only if developing Windows code on Windows machines.
