### ISSUE TITLE
Step 3 Query Component step instructions causing errors

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/carbon-tutorial#2923]
Instructions in step 3 are not working: 
https://www.carbondesignsystem.com/tutorial/react/step-3#query-component

When following this section in step 3, the repo page is broken. 

See this PR for an example: https://github.com/carbon-design-system/carbon-tutorial/pull/2894/files#submit-review

**Comment by IOIO72** [comment]
Here's the breaking change in apollo-react:
https://github.com/apollographql/react-apollo/blob/master/Changelog.md#potentially-breaking-change

So just needed to use `data` instead of `data: {organization}`, 'cause during loading or error state, the `organization` is unknown.

To carbon team:
Possibly just change the instructions for the `Query` function or change `yarn add` to a specific _apollo-react_ version.

**Comment by vpicone** [comment]
@IOIO72 do you mind opening a PR on the carbon website? Would be a super big help.

https://github.com/carbon-design-system/carbon-website

**Comment by IOIO72** [comment]
> @IOIO72 do you mind opening a PR on the carbon website? Would be a super big help.
> 
> https://github.com/carbon-design-system/carbon-website

No problem. I'll do it during the day :)
