### ISSUE TITLE
Step2: Undefined variable: "$spacing-05".

### ISSUE THREAD

**Issue by giacomobartoli** [carbon-design-system/carbon-tutorial#3940]
I've followed your tutorial and my code seems to be fine.
However when I compile I run into this error:

Undefined variable: "$spacing-05".

/src/app.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/app.scss)
    padding-top: $spacing-05;
                ^
      Undefined variable: "$spacing-05".

I guess this should be a context variable available within the framework.
Please check the attached screenshot for more details. Thanks.
![Screen Shot 2020-03-19 at 22 50 57](https://user-images.githubusercontent.com/2913435/77118566-bb36dd00-6a34-11ea-904f-80deb88bd93e.png)

**Comment by giacomobartoli** [comment]
Here you can find the complete code:
https://github.com/giacomobartoli/carbon-tutorial/tree/react-step-2/

Please take a look at /src/content/LandingPage/_landing-page.scss
This file is the one that generates the error and it seems perfectly fine to me.

Thank you

**Comment by hintcnuie** [comment]
yes,  met this issue, too.
I add these import into the _landing-page.scss, but  seems it does not be needed since it is included in the app.scss

```
@import 'carbon-components/scss/globals/scss/vendor/@carbon/type/scss/font-family.scss';
@import 'carbon-components/scss/globals/scss/vendor/@carbon/layout/scss/breakpoint.scss';
@import 'carbon-components/scss/globals/scss/typography.scss';
@import 'carbon-components/scss/globals/scss/vars.scss';
```

**Comment by giacomobartoli** [comment]
@hintcnuie but my imports within app.scss and _landing-page.scss should be fine.
Could you confirm?

**Comment by Daythor8a** [comment]
same issue, solution?

**Comment by giacomobartoli** [comment]
@Daythor8a check the order of the import statements. Apparently it matters.

**Comment by jashukla** [comment]
I got a solution where we can keep all the imports in app.scss so that it's globally available for all components and also issue got resolved.

The solution is to make sure all the imports for carbon-components scss are listed first 
Then the order of imports will turn out to be 

@import 'carbon-components/scss/globals/scss/vendor/@carbon/type/scss/font-family.scss';
@import 'carbon-components/scss/globals/scss/vendor/@carbon/layout/scss/breakpoint.scss';
@import 'carbon-components/scss/globals/scss/typography.scss';
@import 'carbon-components/scss/globals/scss/vars.scss';
@import './components/TutorialHeader/tutorial-header.scss';
@import './content/LandingPage/landing-page.scss';
@import './content/RepoPage/repo-page.scss';

This resolved my issue

**Comment by chaabanetaha** [comment]
The order is the solution as @jashukla  mentioned above !

**Comment by gladishd** [comment]
> @Daythor8a check the order of the import statements. Apparently it matters.

Why yes it does,
```
@import '@carbon/themes/scss/themes';
@import 'carbon-components/scss/globals/scss/styles.scss';

// Use the gray 100 theme
$theme: $theme--g100;
@include theme();
```

This order is the solution!

**Comment by micahkatz** [comment]
In carbon 11, this is what worked for me. I found it on [this StackOverflow thread](https://stackoverflow.com/questions/71808639/how-do-i-fix-carbon-throwing-undefined-mixin-error)

```
@use '@carbon/react/scss/themes';
@use '@carbon/react/scss/theme' with ($theme: themes.$g90);
@use '@carbon/react';
```
