### ISSUE TITLE
`ci check` is failing on Windows

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-tutorial#94]
Changing `'` to `\"` seems to make the command work on Windows. E.g.:

```
    "format": "prettier --write \"**/*.{js,md,scss}\"",
    "format:diff": "prettier --list-different \"**/*.{js,md,scss}\"",
```

**Comment by mattrosno** [comment]
> Running `yarn format` as suggested makes a whole load of changes to file I hadn't touched as it's trying to change between `LF` and `CRLF`. (e.g. it's editing all the `.github/*` files.)

We may need to exclude non-`src` directories in the prettier check and formatting.

**Comment by RoystonS** [comment]
prettier is actually attempting to force all files to LF end-of-line convention. It's doing this because it's reading `.editorconfig` and that says that all files should be LF eol.  That's only appropriate if you're using Unix/Mac, and isn't appropriate on Windows.

**Comment by RoystonS** [comment]
Yup. If I remove the `end_of_line` configuration entry from `.editorconfig` it doesn't attempt to 'fix' all my files by making them LF-based, and doesn't report files that use CRLF as being 'unpretty'.

**Comment by RoystonS** [comment]
The commits I made to fix this:
https://github.com/RoystonS/carbon-tutorial/commit/3bfb6c877bdd894db72365835777ff166e077b8a
https://github.com/RoystonS/carbon-tutorial/commit/13dfb1e3e03259b6ec1543c31bc8b4e5506bc88a

Would you like a PR?

**Comment by mattrosno** [comment]
https://ibm-front-end.slack.com/archives/CJUGA7P6H/p1559070653106100?thread_ts=1559067984.099900&cid=CJUGA7P6H

**Comment by RoystonS** [comment]
@mattrosno Do you want me to raise a separate issue for the `.editorconfig` issue where it forces the use of `LF` line endings?

**Comment by mattrosno** [comment]
@RoystonS I don't think we need to change `.editorconfig`. What editor do you use? As long as your text editor uses the provided editor config, you shouldn't have and `CRLF` line endings, correct?

Also, maybe there was some confusion where `yarn format` prints out every matching file that it found - not every file that it modified. Could it be that it didn't edit all of your `.github/*` files?

```
rosbookibm-5495:carbon-tutorial mattrosno$ yarn format
yarn run v1.15.2
$ prettier --write '**/*.{js,md,scss}'
.github/CODE_OF_CONDUCT.md 56ms
.github/CONTRIBUTING.md 42ms
.github/ISSUE_TEMPLATE/bug_report.md 44ms
.github/ISSUE_TEMPLATE/feature_request.md 14ms
.github/ISSUE_TEMPLATE/question.md 11ms
.github/PULL_REQUEST_TEMPLATE.md 10ms
.github/SUPPORT.md 10ms
README.md 35ms
src/App.js 54ms
src/app.scss 64ms
src/components/TutorialHeader/__tests__/index.test.js 13ms
src/components/TutorialHeader/_tutorial-header.scss 5ms
src/components/TutorialHeader/index.js 5ms
src/components/TutorialHeader/TutorialHeader.js 12ms
src/content/LandingPage/__tests__/index.test.js 8ms
src/content/LandingPage/_landing-page.scss 34ms
src/content/LandingPage/index.js 7ms
src/content/LandingPage/LandingPage.js 30ms
src/content/RepoPage/__tests__/index.test.js 9ms
src/content/RepoPage/_repo-page.scss 6ms
src/content/RepoPage/index.js 10ms
src/content/RepoPage/RepoPage.js 58ms
src/content/RepoPage/RepoTable.js 26ms
src/index.js 11ms
src/index.scss 11ms
src/serviceWorker.js 33ms
src/setupTests.js 17ms
✨  Done in 1.26s.
```

Regardless of your editor's config, the repo has a pre-commit hook called `lint-staged`, which formats all `js`, `scss`, `css`, and `md` files with Prettier, which uses `.editorconfig`, ensuring every committed file consistently has `LF` line endings.

This set-up seems to be working fine with the other Carbon repos. I think the tutorial just needs better instructions to say "`ci-check` script should pass if you've configured your text editor to use `.editorconfig` and format on save - if not, run `format` then `ci-check` - regardless, all files will get formatted in a commit pre-check hook.

**Comment by RoystonS** [comment]
It's not really about the editor:

- By default, git fetches files on Windows with CRLF line endings
- prettier uses the end-of-line setting in .editorconfig to check and format files

So, anybody cloning the repo on Windows and then using `ci-check` will get errors. If they then use `yarn format`, prettier will modify (and it really is modifying, not just printing the name of) _all_ source text files because it will edit every file to change it from CRLF to LF.

(Yes, it really did edit all the .github/* files; they then showed up as changed in git.)

If you want to have a file in the repo (such as .prettierconfig) that's forcing everything to be LF, there should also be an explicit `.gitattributes` file that tells git to check the files out with LF line endings, otherwise git and prettier will fight.

It'll work fine for Mac users, where the default is for git to check out files with LF line endings; it's just a problem for Windows users where the default for git is CRLF.

So there are three options to avoid the fight:

1. _remove_ the explicit LF setting from .editorconfig; prettier will then check that each file is self-consistent, and git will do whatever it needs (typically involving converting CRLF files to LF files at commit time).
1. _add_ explicit `.gitattributes` entries to make the git behaviour match that of the .editorconfig; this is a bit fiddly, and a bit surprising for Windows users as some editors don't like pure-LF files.
1. tell every Windows user that they need to mess about with git's `core.autocrlf`; this is the least friendly option.

**Comment by RoystonS** [comment]
I've raised a separate issue: https://github.com/carbon-design-system/carbon-tutorial/issues/235.
